### ISSUE TITLE
:oncomplete functions don't want to accept an iterator as an argument

### ISSUE THREAD

**Issue by Khranos** [rxi/flux#6]
I'm not sure if this is a bug,an intended feature, or an error on my part, but I felt it'd be worth posting regardless.

Whenever you have a tween inside of an iteration and try to pass the iterator as an argument to the function within :oncomplete, it gives the error "expected function or callable". A (barebones) example of what I'm attempting to do is below:

`
for i, player in ipairs(playerList) do
`
`
    flux.to(player, moveSpeed, {x =xvalue, y = yvalue}):delay(.5):oncomplete(resetAction(player))
`
`
end
`

A temporary solution I've found is that by calling a mediating function with :oncomplete to then call the main function with the arguments, you can get by without an issue.

If you'd like more code to find the issue, I can provide it as soon as possible.

**Comment by rxi** [comment]
Writing the below with assumption that the `resetAction()` function isn't itself returning a function:

The `:oncomplete()` function expects a function as its argument, though `resetAction` is a function you are calling it immediately and its return value is being passed to the `oncomplete` function. The "temporary" solution you mentioned is the actual solution -- this assures a function is being passed which when executed does the `resetAction(player)` call which is the expected behaviour.

The following example may make things more clear:

```lua
local f = function() return 10 end
print( type( f ) ) -- prints "function"
print( type( f() )) -- prints "number"
print( type( function() f() end ) ) -- prints "function"
```

**Comment by Khranos** [comment]
Ah, that makes sense. I greatly appreciate the reply, and apologize for flagging a false "issue". I'll go ahead and close this.
