### ISSUE TITLE
tween:stop() isn't interrupting chains

### ISSUE THREAD

**Issue by MitchellTR** [rxi/flux#7]
Huge fan of this library! One issue/question:

If I chain together multiple tweens in one line of code using flux.to(...):after(...):after(...) and call tween:stop(), it appears that the first tween is stopped and removed from flux.tweens but the others remain and carry out their operations. 

Is this the intended behavior? Is there a preferred method for interrupting multiple tweens this way? For the moment I'm having to use oncomplete() for each new tween so I can safely interrupt any complex events.

Thanks!

**Comment by rxi** [comment]
Just to clarify: each call of `:after()` creates a new tween which is returned (such that `:delay()`, `:ease()` etc. work on the most-recent tween). This means by storing the result of a chain you will get the last tween unless you store the first tween, and then chain onto it. For example:

``` lua
-- `t` is the last tween in the chain:
local t = flux.to(s, 1, { x = 120, y = 120 }):after(s, 1, { size = 100 })

-- `t` is the first tween in the chain:
local t = flux.to(s, 1, { x = 120, y = 120 })
t:after(s, 1, { size = 100 })
```

As `:after()` uses the `:oncomplete()` function internally, stopping the first tween of the chain will only have an effect if it is the current tween, in which case stopping it will also abort the entire chain, otherwise stopping it will do nothing. This applies to each tween, in that only stopping the current tween will have an effect and stop the chain.

This is the current intended behaviour, and does mean you have to hold onto what the "current" tween in a chain is -- or hold onto them all and call stop them all -- which is somewhat cumbersome. I assume this is the approach you are taking now with `:oncomplete()`-- keeping hold of a reference to the current tween each time a new one starts?

Depending on your use case it might be easier to create a `flux.group()` specifically for your chain and simply destroy the group if you want to interrupt the chain -- groups are lightweight so that having many of them is not a problem. I find the approach of each entity and state having its own tween group and having the entity update its own group works well -- it assures an entity's tweens always abide by its timing (pause when it's paused), and that when the entity is killed (stops being updated) all its tweens are effectively killed with it.

**Comment by MitchellTR** [comment]
Fair enough. This was mostly an understanding issue and that explanation helps quite a bit. Thanks!
